const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const colors=['#176b55','#d36b32','#3e6c9d']; let db, turnData, visible=new Set(), selectedRow, momentKinds=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
async function get(url){let r=await fetch(url);if(!r.ok)throw Error(await r.text());return r.json()}
function options(el,vals,label=x=>x){el.innerHTML=vals.map(x=>`<option value="${esc(x)}">${esc(label(x))}</option>`).join('')}
function initTabs(){$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')})}
function initFilters(){let envs=[...new Set(db.trials.map(x=>x.environment))];options($('#environment'),envs);$('#environment').onchange=fillConditions;$('#condition').onchange=fillRuns;$('#run').onchange=fillTurns;$('#turn').onchange=loadTurn;fillConditions()}
function fillConditions(){let e=$('#environment').value, xs=[...new Set(db.trials.filter(x=>x.environment===e).map(x=>x.condition))];options($('#condition'),xs);fillRuns()}
function fillRuns(){let e=$('#environment').value,c=$('#condition').value,xs=db.trials.filter(x=>x.environment===e&&x.condition===c);options($('#run'),xs.map(x=>x.run_id),x=>x.replace(e+'__',''));fillTurns()}
function fillTurns(){let r=$('#run').value,xs=db.turns.filter(x=>x.run_id===r);options($('#turn'),xs.map(x=>x.step),x=>`Step ${x}`);loadTurn()}
async function loadTurn(){let run=$('#run').value,step=$('#turn').value;if(!run)return;turnData=await get(`/api/turn?run_id=${encodeURIComponent(run)}&step=${step}`);selectedRow=null;renderTurn()}
function renderTurn(){let t=turnData.turn,tr=db.trials.find(x=>x.run_id===t.run_id),ms=db.moments.filter(x=>x.run_id===t.run_id);$('#turnTitle').innerHTML=`${esc(t.environment)} / ${esc(t.condition)} · step ${t.step} ${ms.filter(x=>x.step===t.step).map(x=>`<span class="momentBadge ${x.kind}">${x.kind}</span>`).join(' ')}`;$('#trialMeta').innerHTML=`<div class="metaRow"><span>Intent</span><b>${esc(tr.intent_class)}</b></div><div class="metaRow"><span>Tokens</span><b>${fmt(t.selected_message_token_count)}</b></div><div>${['gaming_considered','gaming_attempted','gaming_action','accidental_shortcut'].filter(k=>tr[k]).map(k=>`<span class="badge">${k.replaceAll('_',' ')}</span>`).join('')||'<span class="muted">No active flags</span>'}</div><p class="muted" style="margin-top:10px">${esc(tr.label_notes)}</p>`;$('#runMoments').innerHTML=ms.length?`<div class="runMoments"><b>Annotated moments</b>${ms.map(x=>`<button class="runMoment ${x.step===t.step?'active':''}" data-id="${x.id}"><span class="momentBadge ${x.kind}">${x.kind}</span> step ${x.step}<br>${esc(x.summary)}</button>`).join('')}</div>`:'';$('#runMoments').querySelectorAll('button').forEach(b=>b.onclick=()=>jumpMoment(+b.dataset.id));renderChips();renderChart();renderTokens();$('#inspector').innerHTML='<h3>Token inspector</h3><div class="empty">Select a point or token to see the full J-lens top and bottom tokens.</div>'}
function renderChips(){if(!visible.size)db.meta.candidates.forEach(x=>visible.add(x.name));$('#candidateChips').innerHTML=db.meta.candidates.map((x,i)=>`<button class="chip ${visible.has(x.name)?'':'off'}" data-n="${x.name}"><b style="color:${colors[i]}">●</b> ${x.name}</button>`).join('');$$('.chip').forEach(b=>b.onclick=()=>{visible.has(b.dataset.n)?visible.delete(b.dataset.n):visible.add(b.dataset.n);renderChips();renderChart()})}
function renderChart(){let data=turnData.tokens, names=db.meta.candidates.map(x=>x.name).filter(x=>visible.has(x));if(!data.length||!names.length){$('#chart').innerHTML='<div class="empty" style="padding:20px">No series selected.</div>';return}let W=1000,H=280,p={l:55,r:18,t:20,b:35}, vals=data.flatMap(d=>names.map(n=>d[n])),lo=Math.min(...vals),hi=Math.max(...vals);if(lo===hi){lo--;hi++}let x=i=>p.l+i*(W-p.l-p.r)/Math.max(1,data.length-1),y=v=>p.t+(hi-v)*(H-p.t-p.b)/(hi-lo);let grid='';for(let i=0;i<5;i++){let v=lo+(hi-lo)*i/4,yy=y(v);grid+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="#ddd8cc"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end">${fmt(v)}</text>`}let lines=names.map(n=>{let ci=db.meta.candidates.findIndex(c=>c.name===n),pts=data.map((d,i)=>`${x(i)},${y(d[n])}`).join(' ');return `<polyline points="${pts}" fill="none" stroke="${colors[ci]}" stroke-width="2"/>`}).join('');let dots=data.map((d,i)=>`<circle data-row="${d.row_id}" data-i="${i}" cx="${x(i)}" cy="${y(d[names[0]])}" r="7" fill="transparent"/>`).join('');$('#chart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><g font-size="10" fill="#69716b">${grid}<text x="${W/2}" y="${H-8}" text-anchor="middle">token position</text></g>${lines}${dots}</svg>`;$('#chart').querySelectorAll('circle').forEach(c=>{c.onmousemove=e=>showTip(e,data[+c.dataset.i],names);c.onmouseleave=hideTip;c.onclick=()=>inspect(+c.dataset.row)})}
function showTip(e,d,names){let t=$('#tooltip');t.innerHTML=`<b>${esc(d.token)}</b> · position ${d.token_index_in_turn}<br>${names.map(n=>`${n}: ${fmt(d[n])}`).join('<br>')}`;t.style.cssText=`display:block;left:${e.clientX+12}px;top:${e.clientY+12}px`}function hideTip(){$('#tooltip').style.display='none'}
function renderTokens(){let t=turnData.turn,ms=db.moments.filter(x=>x.run_id===t.run_id&&x.step===t.step),marked=new Set(ms.flatMap(x=>x.highlight_row_ids||[]));$('#tokenStrip').innerHTML=turnData.tokens.map(d=>`<button class="tok ${marked.has(d.row_id)?'gamingPoint':''}" data-row="${d.row_id}" title="${marked.has(d.row_id)?'Reviewed gaming point · ':''}row ${d.row_id}">${esc(d.token).replace(/\n/g,'↵')}</button>`).join('');$$('.tok').forEach(b=>b.onclick=()=>inspect(+b.dataset.row));if(ms.length&&!marked.size)$('#tokenStrip').insertAdjacentHTML('afterbegin','<div class="empty">This turn is labeled, but no precise token span was confidently matched.</div>')}
async function inspect(row){selectedRow=row;$$('.tok').forEach(x=>x.classList.toggle('active',+x.dataset.row===row));let d=await get(`/api/token?row_id=${row}`), names=db.meta.candidates.map(x=>x.name);$('#inspector').innerHTML=`<h3><span class="muted">Token</span> “${esc(d.token)}”</h3><div class="metricGrid">${names.map((n,i)=>`<div class="metric"><span>${n}</span><b style="color:${colors[i]}">${fmt(d.candidates[n].activation)}</b></div>`).join('')}</div><div class="readoutTabs">${Object.keys(d.jlens).map((n,i)=>`<button class="${i?'':'active'}" data-layer="${n}">${n}</button>`).join('')}</div><div id="readout"></div>`;let render=n=>{let r=d.jlens[n];$('#readout').innerHTML=`<div class="definition">${esc(r.definition)}</div><div class="readoutCols">${readoutList('Top',r.top,'positive')}${readoutList('Bottom',r.bottom,'negative')}</div>`};$('#inspector').querySelectorAll('.readoutTabs button').forEach(b=>b.onclick=()=>{$('#inspector').querySelectorAll('.readoutTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.layer)});render(Object.keys(d.jlens)[0])}
function readoutList(title,x,cls){return `<div><b class="${cls}">${title}</b><ul class="readoutList">${x.map(v=>`<li><span>${esc(v.token)}</span><span>${fmt(v.z)}σ</span></li>`).join('')}</ul></div>`}
async function initDirections(){let dirs=await get('/api/directions'), names=Object.keys(dirs);options($('#directionSelect'),names);let draw=()=>{let d=dirs[$('#directionSelect').value],r=d.j_transport_readout,s=db.stats[d.name];$('#directionBody').innerHTML=`<div class="directionGrid"><div class="directionCard"><p class="eyebrow">DIRECTION METRICS</p><div class="bigStat">σ ${fmt(d.sigma)}</div><div class="metaRow"><span>Layer / rank</span><b>L${d.layer} / SV${d.sv_rank}</b></div><div class="metaRow"><span>Identity cosine</span><b>${fmt(d.svd_identity_cosine_Jv_vs_sigmaU)}</b></div><div class="metaRow"><span>Relative error</span><b>${fmt(d.svd_identity_relative_error)}</b></div><div class="definition">${esc(r.definition)}</div><h3>Observed activation range</h3><div class="metaRow"><span>p01 → p99</span><b>${fmt(s.p01)} → ${fmt(s.p99)}</b></div><div class="metaRow"><span>mean ± std</span><b>${fmt(s.mean)} ± ${fmt(s.std)}</b></div></div><div class="directionCard"><div class="readoutCols">${readoutList('Positive Jv',r.top,'positive')}${readoutList('Negative Jv',r.bottom,'negative')}</div></div></div>`};$('#directionSelect').onchange=draw;draw()}
function renderTrials(){let draw=()=>{let q=$('#trialSearch').value.toLowerCase(),xs=db.trials.filter(x=>JSON.stringify(x).toLowerCase().includes(q));$('#trialRows').innerHTML=xs.map(x=>`<tr data-run="${x.run_id}"><td><b>${esc(x.run_id)}</b></td><td>${esc(x.environment)}</td><td>${esc(x.condition)}</td><td>${esc(x.intent_class)}</td><td>${['gaming_considered','gaming_attempted','gaming_action','accidental_shortcut'].filter(k=>x[k]).map(k=>`<span class="badge">${k.replaceAll('_',' ')}</span>`).join('')||'—'}</td><td>${db.turns.filter(t=>t.run_id===x.run_id).length}</td><td>${esc(x.label_notes)}</td></tr>`).join('');$('#trialRows').querySelectorAll('tr').forEach(r=>r.onclick=()=>{let tr=db.trials.find(x=>x.run_id===r.dataset.run);$('#environment').value=tr.environment;fillConditions();$('#condition').value=tr.condition;fillRuns();$('#run').value=tr.run_id;fillTurns();$('.tab[data-tab=tokens]').click()})};$('#trialSearch').oninput=draw;draw()}
function jumpMoment(id){let m=db.moments.find(x=>x.id===id),tr=db.trials.find(x=>x.run_id===m.run_id);$('#environment').value=tr.environment;fillConditions();$('#condition').value=tr.condition;fillRuns();$('#run').value=tr.run_id;fillTurns();$('#turn').value=m.step;loadTurn();window.scrollTo({top:0,behavior:'smooth'})}
function renderMoments(){let kinds=[...new Set(db.moments.map(x=>x.kind))];kinds.forEach(x=>momentKinds.add(x));let draw=()=>{$('#momentFilters').innerHTML=kinds.map(x=>`<button class="chip ${momentKinds.has(x)?'':'off'}" data-kind="${x}">${x}</button>`).join('');$('#momentFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{momentKinds.has(b.dataset.kind)?momentKinds.delete(b.dataset.kind):momentKinds.add(b.dataset.kind);draw()});$('#momentCards').innerHTML=db.moments.filter(x=>momentKinds.has(x.kind)).map(x=>`<button class="momentCard" data-id="${x.id}"><span class="momentBadge ${x.kind}">${x.kind}</span><span class="momentStep">step ${x.step}</span><h3>${esc(x.run_id)}</h3><p>${esc(x.summary)}</p><p class="excerpt">${esc(x.excerpt)}</p></button>`).join('');$('#momentCards').querySelectorAll('button').forEach(b=>b.onclick=()=>jumpMoment(+b.dataset.id))};draw();$('#nextMoment').onclick=()=>jumpMoment(db.moments[0].id)}
(async()=>{initTabs();db=await get('/api/bootstrap');$('#dataset').innerHTML=`${esc(db.meta.model)}<br>${fmt(db.meta.token_rows)} tokens · ${db.meta.manifest_trials} trials · ${db.moments.length} marked moments`;initFilters();initDirections();renderTrials();renderMoments()})().catch(e=>{document.body.innerHTML=`<pre style="padding:30px">Dashboard failed to load:\n${esc(e.stack)}</pre>`});
